# Generated by Django 5.0.6 on 2024-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientV',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('return_limit', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(db_column='IP', max_length=50)),
            ],
            options={
                'db_table': 'client_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('persons_identity_card1', models.TextField(blank=True, null=True)),
                ('persons_identity_card2', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('phone_flag', models.IntegerField(blank=True, null=True)),
                ('email_flag', models.IntegerField(blank=True, null=True)),
                ('id1_flag', models.IntegerField(blank=True, null=True)),
                ('id2_flag', models.IntegerField(blank=True, null=True)),
                ('cases_num', models.IntegerField(blank=True, null=True)),
                ('active_cases_num', models.IntegerField(blank=True, null=True)),
                ('max_debtor_contact_date', models.DateTimeField(blank=True, null=True)),
                ('min_debtor_contact_date', models.DateTimeField(blank=True, null=True)),
                ('max_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('min_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('total_original_debt', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('total_actual_debt', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('max_hist_dpd', models.IntegerField(blank=True, null=True)),
                ('fintech_max_cur_dpd', models.IntegerField(blank=True, null=True)),
                ('max_payment_date', models.DateTimeField(blank=True, null=True)),
                ('payments_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification_v',
                'managed': False,
            },
        ),
    ]
